---
  #
  # Installing Kibana
  #
  
  # Copy tar.gz file to server
  
  - name: Copy tar.gz file to server
    copy:
      src: kibana.tar.gz
      dest: /tmp/kibana.tar.gz
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: 0755
  
  
   # Unarchive source Kibana
  
  - name: Unarchive source Kibana
    unarchive:
      src: /tmp/kibana.tar.gz
      dest: /tmp/
      copy: no
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: 0755
  
  
  # Check the existence of the folder kibana in the directory /elasticsearch
  
  - name: Check the existence of the folder elasticsearch in the directory /elasticsearch
    stat: 
      path: /elasticsearch/kibana/
    register: kibana_exist
  
  
  # Move folder kibana to directory /elasticsearch
  
  - name: Move folder kibana to directory /elasticsearch
    command: mv /tmp/kibana /elasticsearch
    when: kibana_exist.stat.exists == false 
  
  
  # Check the current Kibana symlink
  
  - name: Check the current Kibana symlink
    stat: path=/etc/kibana
    register: kibana_symlink 
  
  
  # Remove the folder Kibana in /etc
  
  - name: Remove the folder Kibana in /etc
    file: path=/etc/kibana state=absent
    when: kibana_symlink.stat.isdir is defined and kibana_symlink.stat.isdir
  
  
  # Create symbolic link
  
  - name: Create symbolic link
    file: 
      src: /elasticsearch/kibana
      dest: /etc/kibana 
      state: link
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: 0644
      force: yes
      follow: false
    
  # Replace default kibana.yml
  
  - name: Replace default kibana.yml
    template:
     src: kibana.yml
     dest: /etc/kibana/config/kibana.yml
     owner: "{{ elasticsearch_user }}"
     group: "{{ elasticsearch_group }}"
     mode: 0644
     force: yes
  
  
  # Create Kibana Service
  
  - name: Kibana | Create Kibana Service
    template: 
      src: kibana.service.j2 
      dest: /lib/systemd/system/kibana.service
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: "u=rw,g=r,o=r"


# Copy sysctl.confs Configuration File
  - name: Copy sysctl.conf Configuration File
    template:
      src: templates/sysctl.conf.j2
      dest: /etc/sysctl.conf
      force: yes
  

 # Copy jvm.options Configuration File

  - name: Copy jvm.options Configuration File
    template:
      src: templates/jvm.options.j2
      dest: /etc/kibana/config/jvm.options
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: 0644
      force: yes
  

  # Permissions
  
  - name: Permissions Kibana User and Group
    command: chown elasticsearch:elasticsearch /elasticsearch -R
  
  
  # Reload Daemon
  
  - name: Reload Daemon
    systemd:
      daemon_reload: yes
  
  
  # Start Kibana Service 
  
  - name: Start Kibana Service
    remote_user: kibana
    service:
      name: kibana
      state: started
      enabled: yes