---
#
# Installing Java 8
#

# Copy rpm file to server

- name: Copy rpm file to server
  copy:
    src: jdk-8u131-linux-x64.rpm
    dest: /tmp/jdk-8u131-linux-x64.rpm


 # Install Java 8

- name: Install Java 8
  yum:
    name: /tmp/jdk-8u131-linux-x64.rpm
    state: present

