---
  #
  # Installing Elasticsearch
  #
  
  # Copy tar.gz file to server
  
  - name: Copy tar.gz file to server
    copy:
      src: elasticsearch.tar.gz
      dest: /tmp/elasticsearch.tar.gz
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: 0755
  
  
   # Unarchive source Elasticsearch
  
  - name: Unarchive source Elasticsearch
    unarchive:
      src: /tmp/elasticsearch.tar.gz
      dest: /tmp/
      copy: no
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: 0755
  
  
  # Check the existence of the folder elasticsearch in the directory /elasticsearch
  
  - name: Check the existence of the folder elasticsearch in the directory /elasticsearch
    stat: 
      path: /elasticsearch/elasticsearch/
    register: elasticsearch_exist
  
  
  # Move folder elasticsearch to directory /elasticsearch
  
  - name: Move folder elasticsearch to directory /elasticsearch
    command: mv /tmp/elasticsearch /elasticsearch
    when: elasticsearch_exist.stat.exists == false 
  
  
  # Check the current Elasticsearch symlink
  
  - name: Check the current Elasticsearch symlink
    stat: path=/etc/elasticsearch
    register: elasticsearch_symlink 
  
  
  # Remove the folder Elasticsearch in /etc
  
  - name: Remove the folder Elasticsearch in /etc
    file: path=/etc/elasticsearch state=absent
    when: elasticsearch_symlink.stat.isdir is defined and elasticsearch_symlink.stat.isdir
  
  
  # Create symbolic link
  
  - name: Create symbolic link
    file: 
      src: /elasticsearch/elasticsearch
      dest: /etc/elasticsearch 
      state: link
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: 0644
      force: yes
      follow: false
    
  # Replace default elasticsearch.yml
  
  - name: Replace default elasticsearch.yml
    template:
     src: elasticsearch.yml
     dest: /etc/elasticsearch/config/elasticsearch.yml
     owner: "{{ elasticsearch_user }}"
     group: "{{ elasticsearch_group }}"
     mode: 0644
     force: yes
  
  
  # Create Elasticsearch Service
  
  - name: Elasticsearch | Create Elasticsearch Service
    template: 
      src: elasticsearch.service.j2 
      dest: /lib/systemd/system/elasticsearch.service
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: "u=rw,g=r,o=r"


# Copy sysctl.confs Configuration File
  - name: Copy sysctl.conf Configuration File
    template:
      src: templates/sysctl.conf.j2
      dest: /etc/sysctl.conf
      force: yes
  

 # Copy jvm.options Configuration File

  - name: Copy jvm.options Configuration File
    template:
      src: templates/jvm.options.j2
      dest: /etc/elasticsearch/config/jvm.options
      owner: "{{ elasticsearch_user }}"
      group: "{{ elasticsearch_group }}"
      mode: 0644
      force: yes
  

  # Permissions
  
  - name: Permissions Elasticsearch User and Group
    command: chown elasticsearch:elasticsearch /elasticsearch -R
  
  
  # Reload Daemon
  
  - name: Reload Daemon
    systemd:
      daemon_reload: yes
  
  
  # Restart Elasticsearch Service 
  
  - name: Restart Elasticsearch Service
    remote_user: elasticsearch
    systemd:
      name: elasticsearch.service
      state: restarted
      daemon_reload: yes
      enabled: yes